name: RobloxAccountManager
options:
  bundleIdPrefix: com.robloxmanager
  createIntermediateGroups: true
  developmentLanguage: en
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

# CryptoKit is a built-in Apple framework, no external package needed

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    CODE_SIGN_IDENTITY: "Apple Development"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: "Automatic"
    ENABLE_HARDENED_RUNTIME: YES
    ENABLE_USER_SELECTED_FILES: readwrite
    ENABLE_DOWNLOADS_FOLDER: readwrite

targets:
  RobloxAccountManager:
    type: application
    platform: macOS
    sources:
      - Sources
      - path: Assets.xcassets
        buildPhase: resources
      - path: Resources
        buildPhase: resources
        excludes:
          - Assets.xcassets/**
    dependencies: []
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.robloxmanager.RobloxAccountManager.v2
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Resources/Info.plist
      properties:
        CFBundleName: "Roblox Account Manager"
        CFBundleDisplayName: "Roblox Account Manager"
        CFBundleIdentifier: "com.robloxmanager.RobloxAccountManager.v2"
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        LSMinimumSystemVersion: "13.0"
        NSHumanReadableCopyright: "© 2024 Roblox Account Manager"
        LSApplicationCategoryType: "public.app-category.utilities"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSRequiresAquaSystemAppearance: false
